In [1]:
import numpy as np

In [2]:
a = [2, 5, 7]

In [3]:
b = [3, 12, 27]

In [4]:
a+b

[2, 5, 7, 3, 12, 27]

In [5]:
c = [m+n for m, n in zip(a,b)]

In [6]:
c

[5, 17, 34]

In [7]:
sum(a)

14

In [8]:
np_a = np.array(a)

In [9]:
np_b = np.array(b)

In [10]:
np_a + np_b

array([ 5, 17, 34])

In [11]:
p = np.array([1,2,"abc"])

In [12]:
p

array(['1', '2', 'abc'], dtype='<U11')

In [13]:
p+ np_a

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [14]:
np_a.max()

7

In [15]:
np_a.mean()

4.666666666666667

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np_a*np.ones(3)

array([2., 5., 7.])

In [19]:
np_a*[3]

array([ 6, 15, 21])

In [20]:
np_a*np.array([2.2])

array([ 4.4, 11. , 15.4])

In [21]:
np_a*np.array([2.2,3.2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [22]:
np_a[1]

5

In [23]:
np_a[1:]

array([5, 7])

In [24]:
np_a[0:2]

array([2, 5])

In [25]:
np_2d = np.array([[1,2],[3,4]])

In [26]:
np_2d.sum()

10

In [27]:
np_2d.sum(axis=0)

array([4, 6])

In [28]:
np_2d.sum(axis=1)

array([3, 7])

In [29]:
np_2d.T()

TypeError: 'numpy.ndarray' object is not callable

In [30]:
np_2d.T

array([[1, 3],
       [2, 4]])

In [31]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [32]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [33]:
np_2d

array([[1, 2],
       [3, 4]])

In [34]:
np_2d+np.ones([2,2])

array([[2., 3.],
       [4., 5.]])

In [35]:
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [36]:
np_2d+np.ones([2,1])

array([[2., 3.],
       [4., 5.]])

In [37]:
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [38]:
np_dotp

array([[2001,  210,  120],
       [4003,  430,  340]])

In [39]:
np_dotp[0,1]

210

In [40]:
np_dotp[1:3]

array([[4003,  430,  340]])

In [41]:
np_dotp[0:2,0]

array([2001, 4003])

In [42]:
np_rs = np.array([1,2,3,4,5,6])

In [43]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [44]:
np_rs.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np_rs.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
np_rs.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np_rs.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [48]:
np_rs.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np_rs.reshape(2,2,-1)

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [50]:
np_rs.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.random(2)

TypeError: 'module' object is not callable

In [52]:
np.random.random(2)

array([0.75059268, 0.91290276])

In [53]:
import np.random as random

ModuleNotFoundError: No module named 'np'

In [54]:
import numpy.random as random

In [55]:
random(2)

TypeError: 'module' object is not callable

In [56]:
random.random(2)

array([0.98347012, 0.92416756])

In [57]:
random.random([3,2])

array([[0.63641807, 0.96683306],
       [0.17219449, 0.46682365],
       [0.1991905 , 0.91502523]])

In [58]:
import numpy.linalg as la

In [59]:
la.inv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [60]:
la.eig(np_2d)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [61]:
la.svd(np_2d)

SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))

In [62]:
la.pinv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [63]:
random.rand(2,3)*5

array([[4.63228606, 3.353759  , 0.90236787],
       [4.18197487, 1.9640273 , 3.34183684]])

In [64]:
random.randn(2,3)

array([[-0.38716334,  0.82208495, -0.17258049],
       [ 2.59882948, -0.34561434, -0.98823199]])

In [65]:
random.randint(-2,3,5)

array([ 0, -2, -1,  1,  2])

In [66]:
random.shuffle(np_rs)

In [67]:
np_rs

array([3, 2, 6, 5, 1, 4])

In [68]:
random.choice(np_rs, 2)

array([6, 3])

In [69]:
random.binomial(20,0.3)

6

In [70]:
random.binomial(20, 0.3, 7)

array([5, 5, 2, 7, 5, 8, 5])

In [71]:
random.exponential(0.7,4)

array([0.28267082, 1.60008884, 0.09383315, 1.30497581])

In [72]:
%%time


UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [73]:
random.normal(-5,12,3)

array([ -1.44826554,  13.72827953, -10.21586284])

In [74]:
random.logistic(-2,4,7)

array([  4.63870623, -14.82457773,  14.18221348,  -4.95462841,
        -1.94369526, -14.01098271,  -1.98941352])

In [75]:
np_2d.shape

(2, 2)

In [76]:
np_2d.dtype

dtype('int32')

In [77]:
type(np_2d)

numpy.ndarray

In [78]:
np.vstack(np.ones([2,2]))

array([[1., 1.],
       [1., 1.]])

In [79]:
np.vstack((np_2d,np.ones([2,2])))

array([[1., 2.],
       [3., 4.],
       [1., 1.],
       [1., 1.]])

In [80]:
np.hstack((np_2d,np.ones([2,2])))

array([[1., 2., 1., 1.],
       [3., 4., 1., 1.]])

In [81]:
N=10000000
x=list(range(N))
y=list(range(N)) 
z=[]

In [82]:
np_x = np.array(x)
np_y = np.array(y)

In [83]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


CPU times: total: 984 ms
Wall time: 1.03 s


In [84]:
%%time
np_z = np_x+np_y

CPU times: total: 0 ns
Wall time: 6.87 ms


Newton Method
Perform this matrix computation -> ((X'X)^-1)*X'y, use only X and y values from rows 2 to 41
Error Computation (both Training and Test Error)
Generate y values from the new generated w values
Compute the SSR, MSR and RMSE between the generated y values and the actual values both for the data from rows 2 to 41 and the data from rows 43 to 51
Regularized Newton
Next step perform the matrix computation -> ((X'X+lambda*I)^-1)*X'y, using only X and y values from rows 2 to 41
Use lambda as 0.17
Compute and report both training and test errors for the regularized newton computation
Compute R-squared values for both Newton and Regularized Newton on both train and test datasets
Look up how to compute R-squared values in excel
Let's try some more things
For each of the below report the following, MSR on train, MSR on test, R-squared on train and R-squared on test
1. Use only rows 2 to 41 for training and rows 42 to 51 for testing and lambda as 0.83
2. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.17
3. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.83
4. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.17
5. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.83


In [106]:
import pandas as pd
import numpy as np

data = pd.read_csv("NumpyExerciseData.csv")
data

X0     X1     X2  X3  X4   X5   y  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0    1  5.768  62.55   0  28  2.6  28         NaN         NaN         NaN   
1    1  8.949  66.91   0  27 -2.0  46         NaN         NaN         NaN   
2    1  1.024  34.42   0  20 -3.4  14         NaN         NaN         NaN   
3    1  4.534  47.93   0  10  1.1  17         NaN         NaN         NaN   
4    1  8.641  35.26   0  30  3.8  32         NaN         NaN         NaN   
5    1  1.063  42.14   0   6 -2.1   8         NaN         NaN         NaN   
6    1  5.306  39.80   0  29 -1.8  30         NaN         NaN         NaN   
7    1  4.309  36.14   0  12 -3.4  22         NaN         NaN         NaN   
8    1  3.739  44.53   0  39  1.9  24         NaN         NaN         NaN   
9    1  3.816  60.01   0  10 -3.4  24         NaN         NaN         NaN   
10   1  8.539  36.90   0  31 -3.0  43         NaN         NaN         NaN   
11   1  7.129  35.77   0  38  3.5  30         NaN         NaN         NaN   
12   1  4.249  37.17   0  23  0.8  20         NaN         NaN         NaN   
13   1 -2.990  42.41   0  20 -3.1   2         NaN         NaN         NaN   
14   1  0.356  57.67   0  26 -3.8  19         NaN         NaN         NaN   
15   1  5.487  35.25   0  10 -2.8  24         NaN         NaN         NaN   
16   1  5.699  62.15   0  13  2.4  22         NaN         NaN         NaN   
17   1 -0.373  38.38   1  42  2.0  23         NaN         NaN         NaN   
18   1  3.900  40.53   0  23 -2.5  25         NaN         NaN         NaN   
19   1  3.616  35.91   1  16  3.1  23         NaN         NaN         NaN   
20   1  9.103  59.60   0  14  2.2  34         NaN         NaN         NaN   
21   1  2.714  43.54   0  37  2.1  19         NaN         NaN         NaN   
22   1  6.885  35.66   1  20 -3.7  46         NaN         NaN         NaN   
23   1 -0.850  43.94   1  31 -3.2  26         NaN         NaN         NaN   
24   1  5.511  58.96   0   6 -3.8  28         NaN         NaN         NaN   
25   1  5.225  45.25   0  24 -1.3  28         NaN         NaN         NaN   
26   1  7.982  43.71   0  27  2.0  33         NaN         NaN         NaN   
27   1  4.361  52.71   0  22 -2.5  28         NaN         NaN         NaN   
28   1  2.853  51.12   0  42  2.3  22         NaN         NaN         NaN   
29   1  2.777  38.60   1  24 -2.5  33         NaN         NaN         NaN   
30   1  1.977  49.07   0  41 -3.6  28         NaN         NaN         NaN   
31   1  3.784  45.44   0  12 -1.9  20         NaN         NaN         NaN   
32   1  3.043  62.50   0  25 -1.9  25         NaN         NaN         NaN   
33   1  5.618  52.44   0  27  1.1  28         NaN         NaN         NaN   
34   1  7.374  38.25   0  36  3.1  31         NaN         NaN         NaN   
35   1  3.090  56.77   0  49 -1.7  33         NaN         NaN         NaN   
36   1  6.178  61.51   1   6 -2.5  41         NaN         NaN         NaN   
37   1  4.605  58.22   0  41  0.2  32         NaN         NaN         NaN   
38   1  1.968  65.84   0  76  3.5  33         NaN         NaN         NaN   
39   1  3.610  45.18   1  43  2.5  36         NaN         NaN         NaN   
40   1  9.896  65.18   0  69  2.3  58         NaN         NaN         NaN   
41   1 -0.256  53.70   0  13  0.3   5         NaN         NaN         NaN   
42   1  4.545  39.25   1  18  2.2  29         NaN         NaN         NaN   
43   1  3.121  36.89   0  20  4.1  10         NaN         NaN         NaN   
44   1  4.698  40.65   0   8 -1.8  20         NaN         NaN         NaN   
45   1 -0.328  49.64   0  18  0.5   6         NaN         NaN         NaN   
46   1  5.216  44.49   1  11  3.2  28         NaN         NaN         NaN   
47   1 -2.111  51.31   0  25  2.6  -1         NaN         NaN         NaN   
48   1  6.804  36.12   0  24  3.0  25         NaN         NaN         NaN   
49   1  5.643  39.06   0  35 -1.9  34         NaN         NaN         NaN   

    Unnamed: 10  
0           NaN  
1           NaN  
2           NaN  
3   

In [107]:
data = data.drop(columns=["Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Unnamed: 10"])
data.head()

X0     X1     X2  X3  X4   X5   y
0   1  5.768  62.55   0  28  2.6  28
1   1  8.949  66.91   0  27 -2.0  46
2   1  1.024  34.42   0  20 -3.4  14
3   1  4.534  47.93   0  10  1.1  17
4   1  8.641  35.26   0  30  3.8  32

Newtons

In [108]:
X = data.iloc[1:41, :6].values
Y = data.iloc[1:41, -1].values

In [109]:
X.shape, Y.shape

((40, 6), (40,))

In [110]:
X = np.hstack((np.ones((X.shape[0], 1)), X))
X

array([[ 1.   ,  1.   ,  8.949, 66.91 ,  0.   , 27.   , -2.   ],
       [ 1.   ,  1.   ,  1.024, 34.42 ,  0.   , 20.   , -3.4  ],
       [ 1.   ,  1.   ,  4.534, 47.93 ,  0.   , 10.   ,  1.1  ],
       [ 1.   ,  1.   ,  8.641, 35.26 ,  0.   , 30.   ,  3.8  ],
       [ 1.   ,  1.   ,  1.063, 42.14 ,  0.   ,  6.   , -2.1  ],
       [ 1.   ,  1.   ,  5.306, 39.8  ,  0.   , 29.   , -1.8  ],
       [ 1.   ,  1.   ,  4.309, 36.14 ,  0.   , 12.   , -3.4  ],
       [ 1.   ,  1.   ,  3.739, 44.53 ,  0.   , 39.   ,  1.9  ],
       [ 1.   ,  1.   ,  3.816, 60.01 ,  0.   , 10.   , -3.4  ],
       [ 1.   ,  1.   ,  8.539, 36.9  ,  0.   , 31.   , -3.   ],
       [ 1.   ,  1.   ,  7.129, 35.77 ,  0.   , 38.   ,  3.5  ],
       [ 1.   ,  1.   ,  4.249, 37.17 ,  0.   , 23.   ,  0.8  ],
       [ 1.   ,  1.   , -2.99 , 42.41 ,  0.   , 20.   , -3.1  ],
       [ 1.   ,  1.   ,  0.356, 57.67 ,  0.   , 26.   , -3.8  ],
       [ 1.   ,  1.   ,  5.487, 35.25 ,  0.   , 10.   , -2.8  ],
       [ 1.   ,  1.   ,  

In [111]:
# computing the pseudo-inverse of (X^T*X)
X_transpose_pseudo_inverse = np.linalg.pinv(np.dot(X.T, X))
X_transpose_pseudo_inverse

array([[ 1.79223696e-01,  1.79223696e-01, -7.70448957e-03,
        -5.51191669e-03, -6.03476345e-02, -1.31260569e-03,
         7.08364373e-03],
       [ 1.79223696e-01,  1.79223696e-01, -7.70448957e-03,
        -5.51191669e-03, -6.03476345e-02, -1.31260569e-03,
         7.08364373e-03],
       [-7.70448957e-03, -7.70448957e-03,  3.74383963e-03,
        -1.43240965e-04,  4.85835606e-03,  1.53264469e-04,
        -1.63683045e-03],
       [-5.51191669e-03, -5.51191669e-03, -1.43240965e-04,
         2.69855722e-04,  1.30388694e-03, -4.84086991e-05,
         1.75956809e-04],
       [-6.03476345e-02, -6.03476345e-02,  4.85835606e-03,
         1.30388694e-03,  1.88171717e-01,  1.38157785e-04,
        -1.46562315e-03],
       [-1.31260569e-03, -1.31260569e-03,  1.53264469e-04,
        -4.84086991e-05,  1.38157785e-04,  1.46161890e-04,
        -4.51876741e-04],
       [ 7.08364373e-03,  7.08364373e-03, -1.63683045e-03,
         1.75956809e-04, -1.46562315e-03, -4.51876741e-04,
         5.4789660

In [112]:
# Weights
w = np.dot(np.dot(X_transpose_pseudo_inverse, X.T), Y)
w

array([-3.91598187, -3.91598187,  3.26458338,  0.16631204, 12.19246692,
        0.38231333, -1.58835343])

In [113]:
# new y values from the generated w values
y_new = np.dot(X, w)
y_new

array([46.00989848, 14.28209844, 17.016938  , 31.67512079,  8.27610001,
       30.05525777, 22.23380488, 23.67253722, 23.82960703, 42.7980017 ,
       30.35890257, 19.74359354,  2.03038794, 18.89733308, 24.21382766,
       22.2672154 , 22.40632288, 24.40462873, 23.33061978, 33.65574554,
       19.07939298, 46.29102151, 25.82780273, 28.29453625, 27.99148376,
       32.64119327, 27.55296899, 22.38771132, 32.9922996 , 28.17596851,
       19.68407044, 25.07237092, 27.80514037, 31.44189406, 33.13068768,
       41.02371652, 32.24130577, 33.03929752, 36.12821698, 58.04097939])

In [114]:
SSR_train = np.sum((Y - y_new) ** 2)
MSR_train = SSR_train / (len(Y))
RMSE_train = np.sqrt(MSR_train)

In [115]:
# getting X_test and y_test values from rows 43 to 50 in matrices
X_test = csv_file.iloc[42:51, :6]
Y_test = csv_file.iloc[42:51, -1]
X_test.shape,y_test.shape



((8, 6), (8,))

In [117]:
# adding a column of ones to X_train
X_test = np.hstack((np.ones((X_test.shape[0], 1)), X_test))
X_test

# computing the pseudo-inverse of (X^T*X)
X_transpose_pseudo_inverse_X1 = np.linalg.pinv(np.dot(X_test.T, X_test))
X_transpose_pseudo_inverse_X1

# computing the weights
weight1 = np.dot(np.dot(X_transpose_pseudo_inverse_X1, X_test.T), y_test)
weight1

# generating y values from the new generated w values
y_new_test = np.dot(X_test, weight1)
y_new_test



array([29.10484845,  9.78787445, 20.23022966,  5.54357092, 27.89515155,
       -0.59718708, 25.13007152, 33.90544053])

In [118]:
SSR_test = np.sum((y_test - y_new_test) ** 2)
MSR_test = SSR_test / (len(y_test))
RMSE_test = np.sqrt(MSR_test)
SSR_test,MSR_test,RMSE_test

(0.5164351933231248, 0.0645543991653906, 0.25407557766418754)

Newton method computation with λ = 0.17

In [119]:
# declaring lambda as 0.17
lambda_reg = 0.17
# computing the pseudo-inverse of (X'X+lambda*I)^-1)
X_transpose_reg_pseudo_inverse_X = np.linalg.pinv(np.dot(X.T, X) + lambda_reg * np.eye(X.shape[1]))
X_transpose_reg_pseudo_inverse_X

array([[ 3.10955194e+00, -2.77280100e+00, -7.21155221e-03,
        -5.18430128e-03, -5.51208106e-02, -1.23548021e-03,
         6.65624171e-03],
       [-2.77280100e+00,  3.10955194e+00, -7.21155221e-03,
        -5.18430128e-03, -5.51208106e-02, -1.23548021e-03,
         6.65624171e-03],
       [-7.21155221e-03, -7.21155221e-03,  3.71835782e-03,
        -1.57619450e-04,  4.56104176e-03,  1.49712910e-04,
        -1.61576960e-03],
       [-5.18430128e-03, -5.18430128e-03, -1.57619450e-04,
         2.59861018e-04,  1.16051135e-03, -5.07276503e-05,
         1.88500927e-04],
       [-5.51208106e-02, -5.51208106e-02,  4.56104176e-03,
         1.16051135e-03,  1.81238711e-01,  1.09090690e-04,
        -1.28527139e-03],
       [-1.23548021e-03, -1.23548021e-03,  1.49712910e-04,
        -5.07276503e-05,  1.09090690e-04,  1.45565569e-04,
        -4.48401970e-04],
       [ 6.65624171e-03,  6.65624171e-03, -1.61576960e-03,
         1.88500927e-04, -1.28527139e-03, -4.48401970e-04,
         5.4570421

In [120]:
# computing the weights
w_reg = np.dot(np.dot(X_transpose_reg_pseudo_inverse_X, X.T), Y)
w_reg

array([-3.57152464, -3.57152464,  3.24302274,  0.1571384 , 11.74050198,
        0.38023007, -1.57443304])

In [121]:
y_new_train_reg = np.dot(X, weight_reg)
y_new_train_reg

array([45.80796927, 14.54418331, 17.16288353, 31.84466659,  8.51378572,
       30.17918901, 22.42595051, 23.81753544, 23.8175737 , 42.85795996,
       30.53552725, 19.96313369,  2.30989592, 18.94246548, 24.40125817,
       22.26944028, 22.23957368, 24.55493279, 23.17000144, 33.60310345,
       19.26252338, 45.9592231 , 25.57086236, 28.25835487, 28.08454158,
       32.72862332, 27.58368188, 22.49067632, 32.7304732 , 28.23657954,
       19.82310111, 25.0437932 , 27.85092551, 31.58908412, 33.10644728,
       40.51589299, 32.21421409, 32.97218107, 35.8180879 , 57.80686318])

Testing Computation

In [122]:
# computing the pseudo-inverse of (X'X+lambda*I)^-1)
X_transpose_pseudo_inverse_X1 = np.linalg.pinv(np.dot(X_test.T, X_test) + lambda_reg * np.eye(X_test.shape[1]))
X_transpose_pseudo_inverse_X1

array([[ 5.41993418e+00, -4.62418762e-01, -4.62418762e-01,
        -1.60050719e-01, -8.90709982e-02,  2.58912544e-01,
        -8.00225386e-03, -5.53532790e-02],
       [-4.62418762e-01,  5.41993418e+00, -4.62418762e-01,
        -1.60050719e-01, -8.90709982e-02,  2.58912544e-01,
        -8.00225386e-03, -5.53532790e-02],
       [-4.62418762e-01, -4.62418762e-01,  5.41993418e+00,
        -1.60050719e-01, -8.90709982e-02,  2.58912544e-01,
        -8.00225386e-03, -5.53532790e-02],
       [-1.60050719e-01, -1.60050719e-01, -1.60050719e-01,
         3.24443786e-02,  9.57495919e-03, -7.84577445e-02,
        -1.33553944e-03,  9.40585201e-03],
       [-8.90709982e-02, -8.90709982e-02, -8.90709982e-02,
         9.57495919e-03,  5.85854451e-03, -2.34383720e-02,
        -4.61410338e-04,  2.70601159e-03],
       [ 2.58912544e-01,  2.58912544e-01,  2.58912544e-01,
        -7.84577445e-02, -2.34383720e-02,  9.39296225e-01,
         1.71921077e-02, -6.69933101e-02],
       [-8.00225386e-03, -8.002253

In [123]:
# computing the weights
w_reg_test = np.dot(np.dot(X_transpose_pseudo_inverse_X1, X_test.T), y_test)
w_reg_test

array([-1.11358864, -1.11358864, -1.11358864,  3.21543962,  0.0912395 ,
       10.47281266,  0.34940367, -1.51916293])

In [125]:
y_new_test_reg = np.dot(X_test, w_reg_test)
y_new_test_reg

array([28.27447775, 10.81995164, 21.00397765,  5.66338317, 26.94514409,
       -0.66179217, 25.66085525, 33.48331269])

In [126]:
SSR_train_reg = np.sum((Y - y_new_train_reg)**2)
MSR_train_reg = SSR_train_reg / (len(Y))
RMSE_train_reg = np.sqrt(MSR_train_reg)
SSR_train_reg,MSR_train_reg,RMSE_train_reg

(4.241977175180815, 0.10604942937952037, 0.32565231364066854)

In [127]:
SSR_test_reg = np.sum((y_test - y_new_test_reg) ** 2)
MSR_test_reg = SSR_test_reg / (len(y_test))
RMSE_test_reg = np.sqrt(MSR_test_reg)
SSR_test_reg,MSR_test_reg,RMSE_test_reg

(4.2507861948126555, 0.5313482743515819, 0.7289363993872043)

In [128]:
#MSR on train, MSR on test, R-squared on train and R-squared on test for the following:
# defining r-squared function
def r_squared(y_actual, y_pred):
    ss_total = np.sum((y_actual - np.mean(y_actual)) ** 2)
    ss_res = np.sum((y_actual - y_pred) ** 2)
    return 1 - (ss_res / ss_total)
# creating a function for the computation of MSR and R-Squared
def computations(train_rows, test_rows, lambda_val):
    
    # extracting X and y values for training
    np_df=pd.read_csv("NumpyExerciseData.csv")
    X_train = np_df.iloc[train_rows[0]:train_rows[1], :6].values
    y_train = np_df.iloc[train_rows[0]:train_rows[1], :6].values
    X_train = np.hstack((np.ones((X_train.shape[0], 1)), X_train))
    
    # extracting X and y values for test
    X_test = np_df.iloc[test_rows[0]:test_rows[1], :6].values
    y_test = np_df.iloc[test_rows[0]:test_rows[1], :6].values
    X_test = np.hstack((np.ones((X_test.shape[0], 1)), X_test))
    
    # regularizing Newton method
    # training computation
    X_reg_pinv_train = np.linalg.pinv(np.dot(X_train.T, X_train) + lambda_val * np.eye(X_train.shape[1])) 
    weight_reg_train = np.dot(np.dot(X_reg_pinv_train, X_train.T), y_train)
    
    # testing computation
    X_reg_pinv_test = np.linalg.pinv(np.dot(X_test.T, X_test) + lambda_val * np.eye(X_test.shape[1])) 
    weight_reg_test = np.dot(np.dot(X_reg_pinv_test, X_test.T), y_test)
    
    # generating y values from the weights
    y_pred_train_reg = np.dot(X_train, weight_reg_train)
    y_pred_test_reg = np.dot(X_test, weight_reg_test)
    
    # computing SSR and MSR for training
    SSR_train_reg = np.sum((y_train - y_pred_train_reg) ** 2)
    MSR_train_reg = SSR_train_reg / (len(y_train))
    
    # computing SSR and MSR for testing
    SSR_test_reg = np.sum((y_test - y_pred_test_reg) ** 2)
    MSR_test_reg = SSR_test_reg / (len(y_test))
    
    # computing R-squared values
    R2_train_reg = r_squared(y_train, y_pred_train_reg)
    R2_test_reg = r_squared(y_test, y_pred_test_reg)
    
    return MSR_train_reg, MSR_test_reg, R2_train_reg, R2_test_reg

In [129]:
results = []

scenarios = [
    ([1, 41], [41, 51], 0.83),
    ([1, 26], [26, 51], 0.17),
    ([1, 26], [26, 51], 0.83),
    ([1, 11], [11, 51], 0.17),
    ([1, 11], [11, 51], 0.83),
]

for scenario in scenarios:
    results.append(computations(*scenario))

# Print results
for i, result in enumerate(results):
    print(f"\nCase {i + 1}: \nMSR Train: {result[0]}, \nMSR Test: {result[1]}, \nR-squared Train: {result[2]}, \nR-squared Test: {result[3]}")


Case 1: 
MSR Train: 0.004285869694921391, 
MSR Test: 0.027773510955230556, 
R-squared Train: 0.9999981579049236, 
R-squared Test: 0.9999826741680861

Case 2: 
MSR Train: 0.000718140088185803, 
MSR Test: 0.0007063155994456374, 
R-squared Train: 0.9999996183026731, 
R-squared Test: 0.9999997188042986

Case 3: 
MSR Train: 0.009844520890582518, 
MSR Test: 0.009789692077646761, 
R-squared Train: 0.9999947675566785, 
R-squared Test: 0.9999961025647283

Case 4: 
MSR Train: 0.0014206402809210312, 
MSR Test: 0.00025047051091725087, 
R-squared Train: 0.9999992385432711, 
R-squared Test: 0.9999998901148855

Case 5: 
MSR Train: 0.013155322708160343, 
MSR Test: 0.00419670111031729, 
R-squared Train: 0.9999929488068645, 
R-squared Test: 0.9999981588452056
